Kernel Autotune E2E pipeline (#2984)
Signed-off-by: patrickji2014 <patrickji2014@gmail.com>

diff --git a/.buildkite/pipeline_kernel_tuning.yml b/.buildkite/pipeline_kernel_tuning.yml
--- a/.buildkite/pipeline_kernel_tuning.yml
+++ b/.buildkite/pipeline_kernel_tuning.yml
@@ -29,14 +29,50 @@
 #     "https://api.buildkite.com/v2/organizations/tpu-commons/pipelines/tpu-inference-kernel-tuning/builds" \
 #     -d "{\"commit\": \"$(git rev-parse HEAD)\", \"branch\": \"$(git rev-parse --abbrev-ref HEAD)\", \"message\": \"my test\"}"
 #
-
 steps:
+  # -----------------------------------------------------------------
+  # -----------------------------------------------------------------
+  - label: "Bootstrap All Kernel Tuning Pipeline"
+    key: bootstrap_all_kernel_tuning_pipeline
+    if: '"${BOOTSTRAP_ALL_KERNEL_TUNING:-}" == "1"'
+    depends_on: build_docker
+    agents:
+      queue: tpu_v6e_queue
+    env:
+      USE_PREBUILT_IMAGE: "1"
+      TPU_VERSION: tpu6e
+    commands:
+      - |
+        # remove the existing generated pipeline YAML in the temp dir on the host. 
+        rm -f "/tmp/kernel_tuning/generated_pipeline.yml"
+      - |
+        .buildkite/scripts/run_in_docker.sh bash -c '
+          generator_script="./tools/kernel/tuner/v1/autotune/bootstrap_kernel_tuners.py"
+          pip install --upgrade -r tools/kernel/tuner/v1/storage_management/requirements.txt
+          if [[ ! -f "$$generator_script" ]]; then
+            echo "🚨 Bootstrap script not found at $$generator_script"
+            exit 1
+          fi
+          if ! py_output=$(python3 "$$generator_script" --autotune_id "$KERNEL_TUNING_AUTOTUNE_ID" 2>&1); then
+            echo "🚨 Failed to bootstrap all kernel tuning for autotune ${KERNEL_TUNING_AUTOTUNE_ID}"
+            exit 1
+          fi
+        '
+      - |
+        # Upload the generated pipeline YAML from the temp dir on the host.
+        buildkite-agent artifact upload "/tmp/kernel_tuning/generated_pipeline.yml"
+        echo "Upload generated pipeline YAML to Buildkite artifacts with priority ${PRIORITY_KERNEL_TUNING}"
+        { 
+          echo "priority: ${PRIORITY_KERNEL_TUNING}"; 
+          cat /tmp/kernel_tuning/generated_pipeline.yml; 
+        } | buildkite-agent pipeline upload
 
 
   # -----------------------------------------------------------------
   # -----------------------------------------------------------------
   - label: ":docker: Tuning Cases Generation and Pipeline Upload (${TPU_VERSION:-tpu6e})"
     key: generate_tuning_cases_and_yml
+    if: '"${BOOTSTRAP_ALL_KERNEL_TUNING:-}" == ""'
     depends_on: build_docker
     env:
       USE_PREBUILT_IMAGE: "1"
@@ -51,8 +87,7 @@ steps:
         .buildkite/scripts/run_in_docker.sh bash -c '
           set -e
           
-          # Combine pip installs to save time
-          pip install --upgrade google-cloud-spanner google-api-core google-auth absl-py
+          python3 -m pip install --upgrade -r tools/kernel/tuner/v1/storage_management/requirements.txt
           
           # Start with the arguments that do not follow the KERNEL_TUNING_ pattern
           PYTHON_ARGS=( 
