fix
Signed-off-by: patrickji2014 <patrickji2014@gmail.com>

diff --git a/.buildkite/pipeline_kernel_tuning.yml b/.buildkite/pipeline_kernel_tuning.yml
--- a/.buildkite/pipeline_kernel_tuning.yml
+++ b/.buildkite/pipeline_kernel_tuning.yml
@@ -53,8 +53,8 @@ steps:
             echo "🚨 Bootstrap script not found at $$generator_script"
             exit 1
           fi
-          if ! py_output=$(python3 "$$generator_script" --auto_tune_id "$KERNEL_TUNING_KERNEL_AUTOTUNE_ID" 2>&1); then
-            echo "🚨 Failed to bootstrap all kernel tuning for autotune ${KERNEL_TUNING_KERNEL_AUTOTUNE_ID}"
+          if ! py_output=$(python3 "$$generator_script" --auto_tune_id "$KERNEL_TUNING_AUTOTUNE_ID" 2>&1); then
+            echo "🚨 Failed to bootstrap all kernel tuning for autotune ${KERNEL_TUNING_AUTOTUNE_ID}"
             exit 1
           fi
         '
