fix
Signed-off-by: patrickji2014 <patrickji2014@gmail.com>

diff --git a/.buildkite/pipeline_kernel_tuning.yml b/.buildkite/pipeline_kernel_tuning.yml
--- a/.buildkite/pipeline_kernel_tuning.yml
+++ b/.buildkite/pipeline_kernel_tuning.yml
@@ -41,27 +41,31 @@ steps:
     env:
       USE_PREBUILT_IMAGE: "1"
       TPU_VERSION: tpu6e
-    commands: |
-      .buildkite/scripts/run_in_docker.sh bash -c '
-        generator_script="./tools/kernel/tuner/v1/autotune/bootstrap_kernel_tuners.py"
-        pip install --upgrade google-cloud-spanner google-api-core google-auth absl-py
-        if [[ ! -f "$$generator_script" ]]; then
-          echo "🚨 Bootstrap script not found at $$generator_script"
-          exit 1
-        fi
-        if ! py_output=$(python3 "$$generator_script" --auto_tune_id "$KERNEL_AUTOTUNE_ID" 2>&1); then
-          echo "🚨 Failed to bootstrap all kernel tuning for autotune ${KERNEL_AUTOTUNE_ID}"
-          exit 1
-        fi
-        echo "$$py_output" | buildkite-agent pipeline upload
+    commands:
+      - |
+        # remove the existing generated pipeline YAML in the temp dir on the host. 
+        rm -f "/tmp/kernel_tuning/generated_pipeline.yml"
+      - |
+        .buildkite/scripts/run_in_docker.sh bash -c '
+          generator_script="./tools/kernel/tuner/v1/autotune/bootstrap_kernel_tuners.py"
+          pip install --upgrade google-cloud-spanner google-api-core google-auth absl-py
+          if [[ ! -f "$$generator_script" ]]; then
+            echo "🚨 Bootstrap script not found at $$generator_script"
+            exit 1
+          fi
+          if ! py_output=$(python3 "$$generator_script" --auto_tune_id "$KERNEL_AUTOTUNE_ID" 2>&1); then
+            echo "🚨 Failed to bootstrap all kernel tuning for autotune ${KERNEL_AUTOTUNE_ID}"
+            exit 1
+          fi
+        '
+      - |
+        # Upload the generated pipeline YAML from the temp dir on the host.
+        buildkite-agent artifact upload "/tmp/kernel_tuning/generated_pipeline.yml"
         echo "Upload generated pipeline YAML to Buildkite artifacts with priority ${PRIORITY_KERNEL_TUNING}"
-        # priority="${PRIORITY_KERNEL_TUNING:-0}"
-
-        # if ! upload_with_priority <(echo "$$py_output") "$$priority"; then
-        #   echo "🚨 Upload failed for all kernel tuning for autotune ${KERNEL_AUTOTUNE_ID}"
-        #   exit 1
-        # fi
-      '
+        { 
+          echo "priority: ${PRIORITY_KERNEL_TUNING}"; 
+          cat /tmp/kernel_tuning/generated_pipeline.yml; 
+        } | buildkite-agent pipeline upload
 
 
   # -----------------------------------------------------------------
