make the run_id and case_set_id required
Signed-off-by: patrick ji <patrickji2014@gmail.com>

diff --git a/.buildkite/pipeline_kernel_tuning.yml b/.buildkite/pipeline_kernel_tuning.yml
--- a/.buildkite/pipeline_kernel_tuning.yml
+++ b/.buildkite/pipeline_kernel_tuning.yml
@@ -64,6 +64,10 @@ steps:
     commands:
       - |
         .buildkite/scripts/run_in_docker.sh bash -c "
+          if [ -z \"\${KERNEL_TUNING_RUN_ID}\" ] || [ -z \"\${KERNEL_TUNING_CASE_SET_ID}\" ]; then
+            echo \"Error: KERNEL_TUNING_RUN_ID or KERNEL_TUNING_CASE_SET_ID not set\"
+            exit 1
+          fi && \
           pip install --upgrade google-cloud-spanner && \
           pip install --upgrade google-api-core && \
           pip install --upgrade google-auth && \
